# Generated by Django 5.2.12 on 2026-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
