# Generated by Django 5.2.12 on 2026-03-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boardpost_slug_boardpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
