# Generated by Django 5.2.12 on 2026-03-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boardpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed/'),
        ),
    ]
