# Generated by Django 5.2.12 on 2026-03-28 15:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_feedpost_image_url_feedpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expires_at),
        ),
    ]
