# Generated by Django 5.2.12 on 2026-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feedpost_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
