# Generated by Django 5.2.12 on 2026-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_boardpost_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_category',
            field=models.CharField(blank=True, choices=[('ktv', 'KTV'), ('massage', 'Massage'), ('full_service', 'Full Service'), ('escort', 'Escort'), ('independent', 'Independent')], max_length=30),
        ),
    ]
