# Generated by Django 5.2.12 on 2026-04-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_bio_profile_location_profile_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=10),
        ),
    ]
