# Generated by Django 5.2.12 on 2026-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_boardpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='board_thumbnails/'),
        ),
    ]
