# Generated by Django 5.2.12 on 2026-04-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boardpost_is_featured_boardpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
